import { MigrationInterface, QueryRunner } from 'typeorm';

// Baseline schema migration — creates all tables, enums, indexes, and
// constraints from scratch.  Must run BEFORE 1718600000000-AddIssueSearchVector.
//
// Generated by reading every @Entity() in src/entities/ and the enums they reference
// in src/common/enums.ts.
export class Baseline1718500000000 implements MigrationInterface {
  name = 'Baseline1718500000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── Enum types ──────────────────────────────────────────────────
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'issue_status_enum') THEN
          CREATE TYPE "issue_status_enum" AS ENUM ('NEW','IN_PROGRESS','ON_HOLD','RESOLVED','CLOSED','REOPENED');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'priority_enum') THEN
          CREATE TYPE "priority_enum" AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'jira_sync_status_enum') THEN
          CREATE TYPE "jira_sync_status_enum" AS ENUM ('NOT_SYNCED','PENDING','SYNCED','FAILED');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'platform_status_enum') THEN
          CREATE TYPE "platform_status_enum" AS ENUM ('ACTIVE','DISABLED');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'account_status_enum') THEN
          CREATE TYPE "account_status_enum" AS ENUM ('ACTIVE','DISABLED');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role_enum') THEN
          CREATE TYPE "role_enum" AS ENUM ('FOCAL_POINT','DEVELOPER','ADMIN');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'comment_visibility_enum') THEN
          CREATE TYPE "comment_visibility_enum" AS ENUM ('INTERNAL','REPORTER_VISIBLE');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'scan_status_enum') THEN
          CREATE TYPE "scan_status_enum" AS ENUM ('PENDING','CLEAN','INFECTED','SKIPPED');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'actor_type_enum') THEN
          CREATE TYPE "actor_type_enum" AS ENUM ('STAFF','SYSTEM','REPORTER');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recipient_type_enum') THEN
          CREATE TYPE "recipient_type_enum" AS ENUM ('STAFF','REPORTER');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_channel_enum') THEN
          CREATE TYPE "notification_channel_enum" AS ENUM ('EMAIL','IN_APP');
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_status_enum') THEN
          CREATE TYPE "notification_status_enum" AS ENUM ('PENDING','SENT','FAILED');
        END IF;
      END $$;
    `);

    // ── Tables (dependency order: independent tables first) ──────

    // platforms
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "platforms" (
        "id"               uuid DEFAULT uuid_generate_v4() NOT NULL,
        "key"              character varying NOT NULL,
        "name"             character varying NOT NULL,
        "status"           "platform_status_enum" NOT NULL DEFAULT 'ACTIVE',
        "jira_project_key" character varying,
        "jira_enabled"     boolean NOT NULL DEFAULT false,
        "handoff_secret"   character varying NOT NULL,
        "created_at"       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_platforms" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_platforms_key" UNIQUE ("key")
      )
    `);

    // staff_users
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "staff_users" (
        "id"            uuid DEFAULT uuid_generate_v4() NOT NULL,
        "idp_subject"   character varying NOT NULL,
        "name"          character varying NOT NULL,
        "email"         character varying NOT NULL,
        "password_hash" character varying,
        "status"        "account_status_enum" NOT NULL DEFAULT 'ACTIVE',
        "created_at"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_staff_users" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_staff_users_idp_subject" UNIQUE ("idp_subject"),
        CONSTRAINT "UQ_staff_users_email" UNIQUE ("email")
      )
    `);

    // reporters (depends on platforms)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "reporters" (
        "id"             uuid DEFAULT uuid_generate_v4() NOT NULL,
        "platform_id"    uuid NOT NULL,
        "portal_user_id" character varying NOT NULL,
        "name"           character varying NOT NULL,
        "email"          character varying NOT NULL,
        "first_seen_at"  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "last_seen_at"   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_reporters" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_reporters_platform_portal" UNIQUE ("platform_id", "portal_user_id"),
        CONSTRAINT "FK_reporters_platform" FOREIGN KEY ("platform_id")
          REFERENCES "platforms" ("id") ON DELETE CASCADE
      )
    `);

    // user_platform_roles (depends on staff_users, platforms)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "user_platform_roles" (
        "id"            uuid DEFAULT uuid_generate_v4() NOT NULL,
        "staff_user_id" uuid NOT NULL,
        "platform_id"   uuid,
        "role"          "role_enum" NOT NULL,
        "created_at"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_user_platform_roles" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_user_platform_roles_user_role_platform" UNIQUE ("staff_user_id", "role", "platform_id"),
        CONSTRAINT "FK_upr_staff_user" FOREIGN KEY ("staff_user_id")
          REFERENCES "staff_users" ("id") ON DELETE CASCADE,
        CONSTRAINT "FK_upr_platform" FOREIGN KEY ("platform_id")
          REFERENCES "platforms" ("id") ON DELETE CASCADE
      )
    `);

    // issues (depends on platforms, reporters, staff_users)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "issues" (
        "id"               uuid DEFAULT uuid_generate_v4() NOT NULL,
        "reference_no"     character varying NOT NULL,
        "platform_id"      uuid,
        "reporter_id"      uuid,
        "assignee_id"      uuid,
        "description"      text NOT NULL,
        "status"           "issue_status_enum" NOT NULL DEFAULT 'NEW',
        "priority"         "priority_enum" NOT NULL DEFAULT 'MEDIUM',
        "jira_issue_key"   character varying,
        "jira_sync_status" "jira_sync_status_enum" NOT NULL DEFAULT 'NOT_SYNCED',
        "version"          integer NOT NULL DEFAULT 1,
        "created_at"       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at"       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "resolved_at"      TIMESTAMP WITH TIME ZONE,
        "closed_at"        TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_issues" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_issues_reference_no" UNIQUE ("reference_no"),
        CONSTRAINT "FK_issues_platform" FOREIGN KEY ("platform_id")
          REFERENCES "platforms" ("id") ON DELETE RESTRICT,
        CONSTRAINT "FK_issues_reporter" FOREIGN KEY ("reporter_id")
          REFERENCES "reporters" ("id") ON DELETE RESTRICT,
        CONSTRAINT "FK_issues_assignee" FOREIGN KEY ("assignee_id")
          REFERENCES "staff_users" ("id") ON DELETE SET NULL
      )
    `);

    // attachments (depends on issues)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "attachments" (
        "id"           uuid DEFAULT uuid_generate_v4() NOT NULL,
        "issue_id"     uuid,
        "storage_key"  character varying NOT NULL,
        "filename"     character varying NOT NULL,
        "content_type" character varying NOT NULL,
        "size_bytes"   integer NOT NULL,
        "scan_status"  "scan_status_enum" NOT NULL DEFAULT 'PENDING',
        "jira_synced"  boolean NOT NULL DEFAULT false,
        "created_at"   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_attachments" PRIMARY KEY ("id"),
        CONSTRAINT "FK_attachments_issue" FOREIGN KEY ("issue_id")
          REFERENCES "issues" ("id") ON DELETE CASCADE
      )
    `);

    // comments (depends on issues, staff_users)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "comments" (
        "id"          uuid DEFAULT uuid_generate_v4() NOT NULL,
        "issue_id"    uuid,
        "author_id"   uuid,
        "author_type" "actor_type_enum" NOT NULL DEFAULT 'STAFF',
        "author_name" character varying,
        "body"        text NOT NULL,
        "visibility"  "comment_visibility_enum" NOT NULL DEFAULT 'INTERNAL',
        "created_at"  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "edited_at"   TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_comments" PRIMARY KEY ("id"),
        CONSTRAINT "FK_comments_issue" FOREIGN KEY ("issue_id")
          REFERENCES "issues" ("id") ON DELETE CASCADE,
        CONSTRAINT "FK_comments_author" FOREIGN KEY ("author_id")
          REFERENCES "staff_users" ("id") ON DELETE SET NULL
      )
    `);

    // audit_events (depends on issues)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "audit_events" (
        "id"         uuid DEFAULT uuid_generate_v4() NOT NULL,
        "issue_id"   uuid,
        "actor_type" "actor_type_enum" NOT NULL,
        "actor_id"   character varying,
        "action"     character varying NOT NULL,
        "field"      character varying,
        "old_value"  character varying,
        "new_value"  character varying,
        "metadata"   jsonb,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_audit_events" PRIMARY KEY ("id"),
        CONSTRAINT "FK_audit_events_issue" FOREIGN KEY ("issue_id")
          REFERENCES "issues" ("id") ON DELETE CASCADE
      )
    `);

    // notification_logs (depends on issues)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "notification_logs" (
        "id"             uuid DEFAULT uuid_generate_v4() NOT NULL,
        "issue_id"       uuid,
        "recipient_type" "recipient_type_enum" NOT NULL,
        "recipient_ref"  character varying NOT NULL,
        "trigger"        character varying NOT NULL,
        "channel"        "notification_channel_enum" NOT NULL,
        "status"         "notification_status_enum" NOT NULL DEFAULT 'PENDING',
        "read_at"        TIMESTAMP WITH TIME ZONE,
        "created_at"     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_notification_logs" PRIMARY KEY ("id"),
        CONSTRAINT "FK_notification_logs_issue" FOREIGN KEY ("issue_id")
          REFERENCES "issues" ("id") ON DELETE CASCADE
      )
    `);

    // reporter_issue_views (depends on reporters, issues)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "reporter_issue_views" (
        "id"             uuid DEFAULT uuid_generate_in_ossp() NOT NULL,
        "reporter_id"    uuid,
        "issue_id"       uuid,
        "last_viewed_at" TIMESTAMP WITH TIME ZONE NOT NULL,
        CONSTRAINT "PK_reporter_issue_views" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_reporter_issue_views_reporter_issue" UNIQUE ("reporter_id", "issue_id"),
        CONSTRAINT "FK_riv_reporter" FOREIGN KEY ("reporter_id")
          REFERENCES "reporters" ("id") ON DELETE CASCADE,
        CONSTRAINT "FK_riv_issue" FOREIGN KEY ("issue_id")
          REFERENCES "issues" ("id") ON DELETE CASCADE
      )
    `);

    // saved_views (depends on staff_users)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "saved_views" (
        "id"            uuid DEFAULT uuid_generate_in_ossp() NOT NULL,
        "staff_user_id" uuid,
        "name"          character varying NOT NULL,
        "filters"       jsonb NOT NULL,
        "created_at"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_saved_views" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_saved_views_user_name" UNIQUE ("staff_user_id", "name"),
        CONSTRAINT "FK_saved_views_staff_user" FOREIGN KEY ("staff_user_id")
          REFERENCES "staff_users" ("id") ON DELETE CASCADE
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop in reverse dependency order.
    await queryRunner.query(`DROP TABLE IF EXISTS "saved_views" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "reporter_issue_views" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "notification_logs" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "audit_events" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "comments" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "attachments" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "issues" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "user_platform_roles" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "reporters" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "staff_users" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "platforms" CASCADE`);

    await queryRunner.query(`DROP TYPE IF EXISTS "notification_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "notification_channel_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "recipient_type_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "actor_type_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "scan_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "comment_visibility_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "role_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "account_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "platform_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "jira_sync_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "priority_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "issue_status_enum"`);
  }
}
